# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: task_management_system_development

test:
  <<: *default
  database: task_management_system_test

production:
  <<: *default
  database: task_management_system_production
  username: task_management_system
  password: <%= ENV['TASK_MANAGEMENT_SYSTEM_DATABASE_PASSWORD'] %>
